[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
Django = "==3.2.6"
django-extensions = "==3.1.3"
django-filter = "==2.4.0"
django-nose = "==1.4.7"
dj-rest-auth = "*"
dj-database-url = "==0.5.0"
django-storages = "==1.11.1"  # https://github.com/jschneier/django-storages
boto3 = "==1.18.26"
djangorestframework = "==3.13.*"
gunicorn = "==20.1.0"
python-decouple = "*"
pytz = "==2021.1"
requests = "==2.*"
whitenoise = "==5.3.0"
psycopg2-binary = "==2.9.1"
django-cors-headers = "==3.8.0"
django-model-utils = "==4.1.1"
drf-yasg = "==1.20.0"
django-multiselectfield = "==0.1.12"
drf-writable-nested = "==0.6.3"
python-slugify = "==5.0.2"
Pillow = "==9.0"
django-currentuser = "==0.5.3"
drf-nested-routers = "==0.93.3"
django-anymail = "==8.4"  # https://github.com/anymail/django-anymail
rollbar = "==0.16.2"
premailer = "*"

[requires]
python_version = "3.10"

[dev-packages]
# Code quality
# ------------------------------------------------------------------------------
flake8 = "*"  # https://github.com/PyCQA/flake8
flake8-isort = "*"  # https://github.com/gforcada/flake8-isort
coverage = "==5.5"  # https://github.com/nedbat/coveragepy
black = "==22.3.0"  # https://github.com/psf/black
pylint-django = "==2.4.4"  # https://github.com/PyCQA/pylint-django
pytest = "==7.1.3"  # Latest version of pytest caused an error. Temporarily pinning
factory-boy = "==3.2.1"
pytest-factoryboy = "==2.5.1"
pytest-cov = "*"
pytest-mccabe = "*"
pre-commit = "==2.13.0"  # https://github.com/pre-commit/pre-commit
# Django Specific
# ------------------------------------------------------------------------------
django-debug-toolbar = "==3.2.1"  # https://github.com/jazzband/django-debug-toolbar
pytest-django = "==4.5.*"  # https://github.com/pytest-dev/pytest-django

[pipenv]
allow_prereleases = true
